# Generated by Django 4.2.5 on 2023-09-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categoria_alter_reserva_categoria_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='email_empresa',
        ),
    ]
